spring.data.mongodb.uri=mongodb://localhost:27017/chattech
spring.ai.google.genai.api-key=AIzaSyCOIRH46V-xY_Ofdu2sI4h4L-hboRXK7ZE
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7
